/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst"
#define EXEC_PREFIX "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst"
#define BINDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/bin"
#define SBINDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/sbin"
#define LIBEXECDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/libexec"
#define DATAROOTDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share"
#define DATADIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share"
#define SYSCONFDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/etc"
#define SHAREDSTATEDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/com"
#define LOCALSTATEDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/var"
#define RUNSTATEDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/var/run"
#define INCLUDEDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/doc/grep"
#define INFODIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/info"
#define HTMLDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/doc/grep"
#define DVIDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/doc/grep"
#define PDFDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/doc/grep"
#define PSDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/doc/grep"
#define LIBDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/lib"
#define LISPDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/emacs/site-lisp"
#define LOCALEDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/locale"
#define MANDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/man"
#define PKGDATADIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/share/grep"
#define PKGINCLUDEDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/include/grep"
#define PKGLIBDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/lib/grep"
#define PKGLIBEXECDIR "/home/mete/shell/testsuites/grep-3.11/grep-3.11/_inst/libexec/grep"
